### ISSUE TITLE
Can't Compile on windows 10 x64

### ISSUE THREAD

**Issue by 0-Satanael** [GerbilSoft/gens-gs-ii#65]
for some reason i can't get it to compile starting from Portaudio to Gens it always ends with an error or it says that there is no C compiler i really like your emulator it has the best renders ever
i used the guide from
https://forums.sonicretro.org/index.php?showtopic=24336
![Untitled](https://user-images.githubusercontent.com/40186693/55667199-76cd2400-5859-11e9-8f09-58eb0f76695e.png)

**Comment by GerbilSoft** [comment]
You might be using original MinGW instead of MinGW-w64. Other than that, I'm not sure.

Also, I haven't really updated Gens/GS II in quite a while, since the codebase has fallen too far behind other emulators and it isn't really worth trying to catch up at this point. For MD and SMS emulation, I'd recommend [https://www.retrodev.com/blastem/](BlastEm).

**Comment by 0-Satanael** [comment]
greetings
thanks for your reply but i have found away better alternative with awesome render and filters
Kega Fusion
https://www.carpeludum.com/kega-fusion/
best regards
